services:
  - type: web
    name: gpt-telegram-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: <вставишь позже>
      - key: OPENAI_API_KEY
        value: <вставишь позже>
